spring:

  application:
    name: supermarket-system

  profiles:
    active: false

  datasource:
    url: jdbc:mysql://localhost:3306/supermarket_provasi?useTimezone=true&serverTimezone=UTC

    username: app_user

    password: senha123

  jpa:

    hibernate:
      ddl-auto: update

    open-in-view: false

    show-sql: true

logging:

  level:
    root: WARN
    br.com.alexdev: INFO